langchain4j:
    open-ai:
        chat-model:
            api-key: ${API_KEY}
            base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
            model-name: qwen-plus
            log-requests: true
            log-responses: true
logging:
    level:
      dev.langchain4j: debug